server:
  port: 8808
  servlet :
    context-path : /tocc
spring:
  datasource:
    primary:
      url: jdbc:postgresql://92.97.136.18:15423/xian_dzk?characterEncoding=UTF-8&allowMultiQueries=true
      username: postgres
      password: cennavi999
      driver-class-name: org.postgresql.Driver

      hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
            max-lifetime: 1800000
    secondary:
      url: jdbc:oracle:thin:@10.173.2.23:1521:orcl
      username: bzdz
      password: bzdz
      driver-class-name: oracle.jdbc.driver.OracleDriver

      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        minimum-idle: 1
        maximum-pool-size: 5
        max-lifetime: 1800000

    third:
      url: jdbc:oracle:thin:@10.173.1.88:1521:sxjfpt2
      username: pgis
      password: pgis
      driver-class-name: oracle.jdbc.driver.OracleDriver

      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        minimum-idle: 1
        maximum-pool-size: 5
        max-lifetime: 1800000


  #redis配置
  redis:
    database: 8
    host: 127.0.0.1
    port: 6379

# ES
#开启 Elasticsearch 仓库(默认值:true)

  data:
    elasticsearch:
      repositories:
        enabled: true
#默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口 #spring.data.elasticsearch.cluster-nodes 集群节点地址列表，用逗号分隔。如果没有指定，就启动一个客户端节点
      cluster-nodes: 92.97.136.17:9300
#spring.data.elasticsearch.cluster-name Elasticsearch 集群名(默认值: elasticsearch)
      cluster-name: elasticsearch
#spring.data.elasticsearch.propertie 用来配置客户端的额外属性
#存储索引的位置
#      properties:
#        path:
#          home: /APP/yndzk/elasticsearch-6.5.4/data
#连接超时的时间
      transport:
        tcp:
          connect_timeout: 120s

  servlet:
    multipart:
       enabled: true
       max-file-size: 10000000000
       max-request-size: 100000000000

swagger:
  enabled: true
  host: 92.97.136.18:19080
